using System;
using TabDock.Models;
using TabDock.Services;
using Xunit;

namespace TabDock.UnitTests;

/// <summary>
/// Deterministic coverage for the unified guest-hide provenance ledger: a
/// queued EVENT_OBJECT_HIDE generated by a TabDock operation must be
/// consumable exactly once by the capture generation that issued it, and an
/// unmatched hide must stay classifiable as guest-initiated.
/// </summary>
public class GuestHideProvenanceTests
{
    private static CapturedWindow Window(long hwnd, long token)
        => new()
        {
            Hwnd = new IntPtr(hwnd),
            ProcessId = 100,
            WindowThreadId = 200,
            WindowIdentityToken = token,
            ExePath = "guest.exe",
            OriginalClassName = "Pig",
        };

    [Fact]
    public void SwitchRoundTrip_DelayedHideArrivingAfterRefocus_IsConsumedNotClassifiedAsSelfHide()
    {
        // A active -> switch to B (TabDock hides A) -> user switches back to A
        // before the queued hide event is dispatched. The late event still
        // belongs to TabDock's switch and must never release the now-active A.
        var provenance = new GuestHideProvenance();
        CapturedWindow a = Window(1, token: 1001);
        provenance.RegisterExpectedHide(a, "tab-switch", eventTime: 5_000);

        bool consumed = provenance.TryConsumeExpectedHide(a.Hwnd, a, eventTime: 5_400, out string operation);

        Assert.True(consumed);
        Assert.Equal("tab-switch", operation);
    }

    [Fact]
    public void RapidSequence_NewestRegistrationSupersedesOlderOnes()
    {
        // A -> B -> C -> A: each switch registers a fresh hide for the window
        // being hidden; only the newest registration per HWND survives.
        var provenance = new GuestHideProvenance();
        CapturedWindow a = Window(1, token: 1001);
        provenance.RegisterExpectedHide(a, "switch-1", eventTime: 1_000);
        provenance.RegisterExpectedHide(a, "switch-2", eventTime: 2_000);

        Assert.True(provenance.TryConsumeExpectedHide(a.Hwnd, a, eventTime: 2_100, out string operation));
        Assert.Equal("switch-2", operation);
        Assert.False(provenance.TryConsumeExpectedHide(a.Hwnd, a, eventTime: 2_200, out _));
    }

    [Fact]
    public void SplitSuspension_HidesOfBothMembers_AreIndependentlyConsumed()
    {
        var provenance = new GuestHideProvenance();
        CapturedWindow left = Window(10, token: 2001);
        CapturedWindow right = Window(20, token: 2002);
        provenance.RegisterExpectedHide(left, "split-suspend", eventTime: 3_000);
        provenance.RegisterExpectedHide(right, "split-suspend", eventTime: 3_000);

        Assert.True(provenance.TryConsumeExpectedHide(left.Hwnd, left, eventTime: 3_050, out _));
        Assert.True(provenance.TryConsumeExpectedHide(right.Hwnd, right, eventTime: 3_060, out _));
        Assert.False(provenance.HasExpectedHide(left.Hwnd));
        Assert.False(provenance.HasExpectedHide(right.Hwnd));
    }

    [Fact]
    public void ContainerMinimize_HideConsumedEvenWhenDeliveredAfterRestore()
    {
        var provenance = new GuestHideProvenance();
        CapturedWindow a = Window(1, token: 1001);
        provenance.RegisterExpectedHide(a, "container-minimize", eventTime: 4_000);

        // Delivered after WPF already reported the restored state.
        Assert.True(provenance.TryConsumeExpectedHide(a.Hwnd, a, eventTime: 4_900, out _));
    }

    [Fact]
    public void GenuineTrayClose_NoRegistration_NotConsumed()
    {
        var provenance = new GuestHideProvenance();
        CapturedWindow a = Window(1, token: 1001);

        Assert.False(provenance.TryConsumeExpectedHide(a.Hwnd, a, eventTime: 9_000, out _));
    }

    [Fact]
    public void RecycledHwnd_StaleExpectationForPreviousGeneration_NeverMatchesNewMember()
    {
        var provenance = new GuestHideProvenance();
        CapturedWindow original = Window(1, token: 1001);
        provenance.RegisterExpectedHide(original, "tab-switch", eventTime: 1_000);

        // Same numeric HWND recycled into a NEW capture generation.
        CapturedWindow replacement = Window(1, token: 4242);

        Assert.False(provenance.TryConsumeExpectedHide(replacement.Hwnd, replacement, eventTime: 1_050, out _));
        // The stale expectation was dropped with the mismatch, so it cannot be
        // replayed against any later member either.
        Assert.False(provenance.HasExpectedHide(replacement.Hwnd));
    }

    [Fact]
    public void RemovedMember_DelayedEventAfterForget_IsNotConsumed()
    {
        var provenance = new GuestHideProvenance();
        CapturedWindow a = Window(1, token: 1001);
        provenance.RegisterExpectedHide(a, "tab-switch", eventTime: 1_000);
        provenance.ForgetWindow(a.Hwnd);

        Assert.False(provenance.TryConsumeExpectedHide(a.Hwnd, a, eventTime: 1_050, out _));
    }

    [Fact]
    public void ConsumptionIsOneShot_SecondIdenticalEventFailsClosed()
    {
        var provenance = new GuestHideProvenance();
        CapturedWindow a = Window(1, token: 1001);
        provenance.RegisterExpectedHide(a, "tab-switch", eventTime: 1_000);

        Assert.True(provenance.TryConsumeExpectedHide(a.Hwnd, a, eventTime: 1_010, out _));
        Assert.False(provenance.TryConsumeExpectedHide(a.Hwnd, a, eventTime: 1_020, out _));
    }

    [Fact]
    public void EventBeyondTolerance_FailsClosedAndDropsExpectation()
    {
        var provenance = new GuestHideProvenance(toleranceMilliseconds: 1_000);
        CapturedWindow a = Window(1, token: 1001);
        provenance.RegisterExpectedHide(a, "container-minimize", eventTime: 10_000);

        // Far beyond the delivery tolerance: this cannot be proven to belong
        // to the registered operation, so classification proceeds unmatched.
        Assert.False(provenance.TryConsumeExpectedHide(a.Hwnd, a, eventTime: 60_000, out _));
        Assert.False(provenance.HasExpectedHide(a.Hwnd));
    }

    [Fact]
    public void MissingTimestamp_FailsClosed()
    {
        var provenance = new GuestHideProvenance();
        CapturedWindow a = Window(1, token: 1001);
        provenance.RegisterExpectedHide(a, "tab-switch", eventTime: 1_000);

        Assert.False(provenance.TryConsumeExpectedHide(a.Hwnd, a, eventTime: 0, out _));
    }

    [Fact]
    public void RegistrationWithoutCaptureToken_IsIgnored()
    {
        var provenance = new GuestHideProvenance();
        CapturedWindow anonymous = Window(1, token: 0);

        provenance.RegisterExpectedHide(anonymous, "tab-switch", eventTime: 1_000);

        Assert.False(provenance.HasExpectedHide(anonymous.Hwnd));
    }
}
